/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CallIndexRouteImport } from './routes/call.index'
import { Route as CallAgentsRouteImport } from './routes/call.agents'
import { Route as CallCampaignsRouteImport } from './routes/call.campaigns'
import { Route as CallHistoryRouteImport } from './routes/call.history'
import { Route as CallHopperRouteImport } from './routes/call.hopper'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as HostDeploymentsRouteImport } from './routes/host.deployments'
import { Route as HostDnsRouteImport } from './routes/host.dns'
import { Route as HostDomainsRouteImport } from './routes/host.domains'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsAllRouteImport } from './routes/leads.all'
import { Route as LeadsImportRouteImport } from './routes/leads.import'
import { Route as LeadsSuppressionRouteImport } from './routes/leads.suppression'
import { Route as MailerIndexRouteImport } from './routes/mailer.index'
import { Route as MailerCampaignsRouteImport } from './routes/mailer.campaigns'
import { Route as MailerDeliverabilityRouteImport } from './routes/mailer.deliverability'
import { Route as MailerMailboxesRouteImport } from './routes/mailer.mailboxes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CallIndexRoute = CallIndexRouteImport.update({
  id: '/call/',
  path: '/call/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallAgentsRoute = CallAgentsRouteImport.update({
  id: '/call/agents',
  path: '/call/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCampaignsRoute = CallCampaignsRouteImport.update({
  id: '/call/campaigns',
  path: '/call/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CallHistoryRoute = CallHistoryRouteImport.update({
  id: '/call/history',
  path: '/call/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CallHopperRoute = CallHopperRouteImport.update({
  id: '/call/hopper',
  path: '/call/hopper',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/host/',
  path: '/host/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDeploymentsRoute = HostDeploymentsRouteImport.update({
  id: '/host/deployments',
  path: '/host/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDnsRoute = HostDnsRouteImport.update({
  id: '/host/dns',
  path: '/host/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const HostDomainsRoute = HostDomainsRouteImport.update({
  id: '/host/domains',
  path: '/host/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsAllRoute = LeadsAllRouteImport.update({
  id: '/leads/all',
  path: '/leads/all',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsImportRoute = LeadsImportRouteImport.update({
  id: '/leads/import',
  path: '/leads/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsSuppressionRoute = LeadsSuppressionRouteImport.update({
  id: '/leads/suppression',
  path: '/leads/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const MailerIndexRoute = MailerIndexRouteImport.update({
  id: '/mailer/',
  path: '/mailer/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailerCampaignsRoute = MailerCampaignsRouteImport.update({
  id: '/mailer/campaigns',
  path: '/mailer/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const MailerDeliverabilityRoute = MailerDeliverabilityRouteImport.update({
  id: '/mailer/deliverability',
  path: '/mailer/deliverability',
  getParentRoute: () => rootRouteImport,
} as any)
const MailerMailboxesRoute = MailerMailboxesRouteImport.update({
  id: '/mailer/mailboxes',
  path: '/mailer/mailboxes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/call/agents': typeof CallAgentsRoute
  '/call/campaigns': typeof CallCampaignsRoute
  '/call/history': typeof CallHistoryRoute
  '/call/hopper': typeof CallHopperRoute
  '/host/deployments': typeof HostDeploymentsRoute
  '/host/dns': typeof HostDnsRoute
  '/host/domains': typeof HostDomainsRoute
  '/leads/all': typeof LeadsAllRoute
  '/leads/import': typeof LeadsImportRoute
  '/leads/suppression': typeof LeadsSuppressionRoute
  '/mailer/campaigns': typeof MailerCampaignsRoute
  '/mailer/deliverability': typeof MailerDeliverabilityRoute
  '/mailer/mailboxes': typeof MailerMailboxesRoute
  '/admin/': typeof AdminIndexRoute
  '/call/': typeof CallIndexRoute
  '/host/': typeof HostIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/mailer/': typeof MailerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/call/agents': typeof CallAgentsRoute
  '/call/campaigns': typeof CallCampaignsRoute
  '/call/history': typeof CallHistoryRoute
  '/call/hopper': typeof CallHopperRoute
  '/host/deployments': typeof HostDeploymentsRoute
  '/host/dns': typeof HostDnsRoute
  '/host/domains': typeof HostDomainsRoute
  '/leads/all': typeof LeadsAllRoute
  '/leads/import': typeof LeadsImportRoute
  '/leads/suppression': typeof LeadsSuppressionRoute
  '/mailer/campaigns': typeof MailerCampaignsRoute
  '/mailer/deliverability': typeof MailerDeliverabilityRoute
  '/mailer/mailboxes': typeof MailerMailboxesRoute
  '/admin': typeof AdminIndexRoute
  '/call': typeof CallIndexRoute
  '/host': typeof HostIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/mailer': typeof MailerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/call/agents': typeof CallAgentsRoute
  '/call/campaigns': typeof CallCampaignsRoute
  '/call/history': typeof CallHistoryRoute
  '/call/hopper': typeof CallHopperRoute
  '/host/deployments': typeof HostDeploymentsRoute
  '/host/dns': typeof HostDnsRoute
  '/host/domains': typeof HostDomainsRoute
  '/leads/all': typeof LeadsAllRoute
  '/leads/import': typeof LeadsImportRoute
  '/leads/suppression': typeof LeadsSuppressionRoute
  '/mailer/campaigns': typeof MailerCampaignsRoute
  '/mailer/deliverability': typeof MailerDeliverabilityRoute
  '/mailer/mailboxes': typeof MailerMailboxesRoute
  '/admin/': typeof AdminIndexRoute
  '/call/': typeof CallIndexRoute
  '/host/': typeof HostIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/mailer/': typeof MailerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin/audit'
    | '/admin/integrations'
    | '/admin/roles'
    | '/admin/users'
    | '/call/agents'
    | '/call/campaigns'
    | '/call/history'
    | '/call/hopper'
    | '/host/deployments'
    | '/host/dns'
    | '/host/domains'
    | '/leads/all'
    | '/leads/import'
    | '/leads/suppression'
    | '/mailer/campaigns'
    | '/mailer/deliverability'
    | '/mailer/mailboxes'
    | '/admin/'
    | '/call/'
    | '/host/'
    | '/leads/'
    | '/mailer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/admin/audit'
    | '/admin/integrations'
    | '/admin/roles'
    | '/admin/users'
    | '/call/agents'
    | '/call/campaigns'
    | '/call/history'
    | '/call/hopper'
    | '/host/deployments'
    | '/host/dns'
    | '/host/domains'
    | '/leads/all'
    | '/leads/import'
    | '/leads/suppression'
    | '/mailer/campaigns'
    | '/mailer/deliverability'
    | '/mailer/mailboxes'
    | '/admin'
    | '/call'
    | '/host'
    | '/leads'
    | '/mailer'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin/audit'
    | '/admin/integrations'
    | '/admin/roles'
    | '/admin/users'
    | '/call/agents'
    | '/call/campaigns'
    | '/call/history'
    | '/call/hopper'
    | '/host/deployments'
    | '/host/dns'
    | '/host/domains'
    | '/leads/all'
    | '/leads/import'
    | '/leads/suppression'
    | '/mailer/campaigns'
    | '/mailer/deliverability'
    | '/mailer/mailboxes'
    | '/admin/'
    | '/call/'
    | '/host/'
    | '/leads/'
    | '/mailer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CallAgentsRoute: typeof CallAgentsRoute
  CallCampaignsRoute: typeof CallCampaignsRoute
  CallHistoryRoute: typeof CallHistoryRoute
  CallHopperRoute: typeof CallHopperRoute
  HostDeploymentsRoute: typeof HostDeploymentsRoute
  HostDnsRoute: typeof HostDnsRoute
  HostDomainsRoute: typeof HostDomainsRoute
  LeadsAllRoute: typeof LeadsAllRoute
  LeadsImportRoute: typeof LeadsImportRoute
  LeadsSuppressionRoute: typeof LeadsSuppressionRoute
  MailerCampaignsRoute: typeof MailerCampaignsRoute
  MailerDeliverabilityRoute: typeof MailerDeliverabilityRoute
  MailerMailboxesRoute: typeof MailerMailboxesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CallIndexRoute: typeof CallIndexRoute
  HostIndexRoute: typeof HostIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  MailerIndexRoute: typeof MailerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/': {
      id: '/call/'
      path: '/call'
      fullPath: '/call/'
      preLoaderRoute: typeof CallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/agents': {
      id: '/call/agents'
      path: '/call/agents'
      fullPath: '/call/agents'
      preLoaderRoute: typeof CallAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/campaigns': {
      id: '/call/campaigns'
      path: '/call/campaigns'
      fullPath: '/call/campaigns'
      preLoaderRoute: typeof CallCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/history': {
      id: '/call/history'
      path: '/call/history'
      fullPath: '/call/history'
      preLoaderRoute: typeof CallHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/hopper': {
      id: '/call/hopper'
      path: '/call/hopper'
      fullPath: '/call/hopper'
      preLoaderRoute: typeof CallHopperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/host'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/deployments': {
      id: '/host/deployments'
      path: '/host/deployments'
      fullPath: '/host/deployments'
      preLoaderRoute: typeof HostDeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/dns': {
      id: '/host/dns'
      path: '/host/dns'
      fullPath: '/host/dns'
      preLoaderRoute: typeof HostDnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/domains': {
      id: '/host/domains'
      path: '/host/domains'
      fullPath: '/host/domains'
      preLoaderRoute: typeof HostDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/all': {
      id: '/leads/all'
      path: '/leads/all'
      fullPath: '/leads/all'
      preLoaderRoute: typeof LeadsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/import': {
      id: '/leads/import'
      path: '/leads/import'
      fullPath: '/leads/import'
      preLoaderRoute: typeof LeadsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/suppression': {
      id: '/leads/suppression'
      path: '/leads/suppression'
      fullPath: '/leads/suppression'
      preLoaderRoute: typeof LeadsSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailer/': {
      id: '/mailer/'
      path: '/mailer'
      fullPath: '/mailer/'
      preLoaderRoute: typeof MailerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailer/campaigns': {
      id: '/mailer/campaigns'
      path: '/mailer/campaigns'
      fullPath: '/mailer/campaigns'
      preLoaderRoute: typeof MailerCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailer/deliverability': {
      id: '/mailer/deliverability'
      path: '/mailer/deliverability'
      fullPath: '/mailer/deliverability'
      preLoaderRoute: typeof MailerDeliverabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailer/mailboxes': {
      id: '/mailer/mailboxes'
      path: '/mailer/mailboxes'
      fullPath: '/mailer/mailboxes'
      preLoaderRoute: typeof MailerMailboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  CallAgentsRoute: CallAgentsRoute,
  CallCampaignsRoute: CallCampaignsRoute,
  CallHistoryRoute: CallHistoryRoute,
  CallHopperRoute: CallHopperRoute,
  HostDeploymentsRoute: HostDeploymentsRoute,
  HostDnsRoute: HostDnsRoute,
  HostDomainsRoute: HostDomainsRoute,
  LeadsAllRoute: LeadsAllRoute,
  LeadsImportRoute: LeadsImportRoute,
  LeadsSuppressionRoute: LeadsSuppressionRoute,
  MailerCampaignsRoute: MailerCampaignsRoute,
  MailerDeliverabilityRoute: MailerDeliverabilityRoute,
  MailerMailboxesRoute: MailerMailboxesRoute,
  AdminIndexRoute: AdminIndexRoute,
  CallIndexRoute: CallIndexRoute,
  HostIndexRoute: HostIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  MailerIndexRoute: MailerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
